name: dotnet package

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore CurrencyApi/CurrencyApi.csproj
      - name: Build
        run: dotnet build CurrencyApi/CurrencyApi.csproj
      - name: Publish
        run: dotnet publish CurrencyApi/CurrencyApi.csproj -c Release -o web
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: web
      