name: dotnet package

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: poc-github-testing
  DOTNET_VERSION: '8.0.x'          
  AZURE_RESOURCEGROUP_NAME: prod-rg-weu-web 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: dotnet build and publish
        run: |
          dotnet restore CurrencyApi/CurrencyApi.csproj
          dotnet build CurrencyApi/CurrencyApi.csproj -c Release 
          dotnet publish CurrencyApi/CurrencyApi.csproj -c Release -o ./web
          
      - name: web
        uses: actions/upload-artifact@v4
        with:
          name: web-artifact
          path: ./web
      