name: dotnet package

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: poc-github-testing
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'          
  AZURE_RESOURCEGROUP_NAME: prod-rg-weu-web 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: dotnet build and publish
        run: |
          dotnet restore CurrencyApi/CurrencyApi.csproj
          dotnet build CurrencyApi/CurrencyApi.csproj -c Release 
          dotnet publish CurrencyApi/CurrencyApi.csproj -c Release o ./web
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: ./web
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: ./web
        
      