name: publish
on:
  workflow_run:
    workflows: [build]
    branches: [main]
    types: [completed]

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: poc-github-testing
  AZURE_RESOURCEGROUP_NAME: prod-rg-weu-web 

jobs:
  deployment:
    name: Deploy to dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Get run ID of "build" workflow
        id: get-run-id
        run: |
          OTHER_REPO="${{ github.repository }}"
          WF_NAME="build"
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: dotnet build and publish
        run: |
          echo "AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}"

      - uses: actions/download-artifact@v4
        with:
          name: web-artifact
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-run-id.outputs.run-id }}

      - name: Display structure of downloaded files
        run: ls -R
          
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      
      - name: Run Azure webapp deploy
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: .
        
      