name: publish web app

on:
  release:
    types: [published]
  workflow_dispatch: 
    inputs:
      releaseType:
        description: 'Release to dev'

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: poc-github-testing
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'          
  AZURE_RESOURCEGROUP_NAME: prod-rg-weu-web 

jobs:
  dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web-artifact
          
      - name: Display structure of downloaded files
        run: ls -R
          
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      
      - name: Run Azure webapp deploy
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: ./web
        
      